### ISSUE TITLE
Integrate subtitle download from opensubtitle or other source

### ISSUE THREAD

**Issue by Riaz-404** [joshholly/VidBinge#10]
### What feature do you want to add?

Adding integrating subtitles downloading feature from online sources like opensubtitle or others

### Why do you want to have this feature?

I have been using sudo-flex. Recently they have been shut down, so I started using vidbinge. It is almost the same as sudo-flex. But I have found it does not support to download subtitles from online sources as sudo-flex did. In some videos, I found the integrated subtitle is not accurate. So downloading directly from other sources will help to find the corrected subtitles. That's why I'm suggesting integrating downloading subtitles from online sources like opensubtitle or others.

**Comment by AbdullahDaGoat** [comment]
Hey there you should join our discord serve --> https://discord.gg/7EE5D4apFV!

I am a server admin this feature has been resolved today and we are actively working on ensuring streamlined incorporation. Thanks so much for your suggestion!

**Comment by joshholly** [comment]
We added it!
