### ISSUE TITLE
What cors proxy is your using?

### ISSUE THREAD

**Issue by harshascode** [joshholly/VidBinge#16]
How can I deploy this in cloudflair? Is there any docs or resources I can use.

**Comment by The-UnknownHacker** [comment]
This is the proxy documentation for sudo-flix but the setup should be similar
https://docs.undi.rest/proxy/deploy

**Comment by harshascode** [comment]
Thanks a lot.

**Comment by The-UnknownHacker** [comment]
Welcome

**Comment by harshascode** [comment]
I deployed the site. but its not good as vidbinge. my website failed to scrape top 4 sources. my proxy working fine. do you know any solution for this or what i doing wrong here.


![Screenshot_2024-08-01_22-43-04](https://github.com/user-attachments/assets/88ac3681-7769-4e57-93fb-f27937c5f8e7)

**Comment by The-UnknownHacker** [comment]
Have you checked the TMDB Api keys as well as the scraper keys

**Comment by harshascode** [comment]
in dev mode the website works perfectly. i found that my proxy not working properly i tried multiple times. it always say its working in web page. but in gitpod when we hit the proxy form scrapper it giving some errors. i have no idea how to fix this. do you have any idea how to fix this.

This is the error log:
Listening on http://[::]:3000
[nitro] [request error] [unhandled] Cannot set headers after they are sent to the client
  at ServerResponse.setHeader (node:_http_outgoing:659:11)  
  at defaultContentType (./.output/server/chunks/runtime.mjs:2228:20)  
  at send (./.output/server/chunks/runtime.mjs:2190:5)  
  at handleHandlerResponse (./.output/server/chunks/runtime.mjs:3008:12)  
  at Object.handler (./.output/server/chunks/runtime.mjs:2904:15)  
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3166:7)
[nitro] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:659:11)
    at setResponseHeader (file:///workspace/movie-proxy/.output/server/chunks/runtime.mjs:2254:18)
    at defaultNitroErrorHandler (file:///workspace/movie-proxy/.output/server/chunks/runtime.mjs:5173:7)
    at Object.onError (file:///workspace/movie-proxy/.output/server/chunks/runtime.mjs:5437:14)
    at Server.toNodeHandle (file:///workspace/movie-proxy/.output/server/chunks/runtime.mjs:3174:27) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by joshholly** [comment]
> I deployed the site. but its not good as vidbinge. my website failed to scrape top 4 sources. my proxy working fine. do you know any solution for this or what i doing wrong here.
> 
> ![Screenshot_2024-08-01_22-43-04](https://private-user-images.githubusercontent.com/118063362/354317799-88ac3681-7769-4e57-93fb-f27937c5f8e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDMzODEsIm5iZiI6MTcyMjY0MzA4MSwicGF0aCI6Ii8xMTgwNjMzNjIvMzU0MzE3Nzk5LTg4YWMzNjgxLTc3NjktNGU1Ny05M2ZiLWYyNzkzN2M1ZjhlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQyMzU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGE4N2Q0ZmExM2Y0NjFmNTg5ZGFkZWY2OGE3MDdkN2NiOGJmMmY2ZTQ4ODA4ZTI1MjUzZDI5NmM5NDgyMmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YVUPwtU6DSqGsAiktLMPP03LVT1HYF-cPbLl0vp3cYg)

So WHVX and NSBX are private sources and only work on vidbinge and our partners. You may have to go into your providers, fork it, and pull the providers from your own fork with whvx and nsbx disabled.

**Comment by harshascode** [comment]
ok, now i understand why scrappers not working in my project. thank you for clarifying.
