### ISSUE TITLE
Dubbed Audio

### ISSUE THREAD

**Issue by adilurrhmn** [joshholly/VidBinge#8]
### What feature do you want to add?

There is no Hindi Dubbed audios for English movies like iron man, Twilight 

### Why do you want to have this feature?

If it supports multi audios then everyone will watch in their understanding language

**Comment by joshholly** [comment]
Hello. It all depends on the source. I will be adding sources that have more Hidni dubs. A lot of movies do have Hindi subs, which you can select the subtitle of your language.

**Comment by adilurrhmn** [comment]
Already texted you in facebook

**Comment by joshholly** [comment]
Hello. We added a source called "Autoembed". This source has Hindi and a bunch of other dubs to many movies.

**Comment by adilurrhmn** [comment]
Okay... Thank you

**Comment by adilurrhmn** [comment]
Autoembed doesn't work, Can you add streamwish source from primewire
